var namespace_sharp_nav =
[
    [ "Collections", "namespace_sharp_nav_1_1_collections.html", "namespace_sharp_nav_1_1_collections" ],
    [ "Crowds", "namespace_sharp_nav_1_1_crowds.html", "namespace_sharp_nav_1_1_crowds" ],
    [ "Geometry", "namespace_sharp_nav_1_1_geometry.html", "namespace_sharp_nav_1_1_geometry" ],
    [ "Pathfinding", "namespace_sharp_nav_1_1_pathfinding.html", "namespace_sharp_nav_1_1_pathfinding" ],
    [ "Area", "struct_sharp_nav_1_1_area.html", "struct_sharp_nav_1_1_area" ],
    [ "AreaGenerator", "class_sharp_nav_1_1_area_generator.html", "class_sharp_nav_1_1_area_generator" ],
    [ "Cell", "class_sharp_nav_1_1_cell.html", "class_sharp_nav_1_1_cell" ],
    [ "CompactCell", "struct_sharp_nav_1_1_compact_cell.html", "struct_sharp_nav_1_1_compact_cell" ],
    [ "CompactHeightfield", "class_sharp_nav_1_1_compact_heightfield.html", "class_sharp_nav_1_1_compact_heightfield" ],
    [ "CompactSpan", "struct_sharp_nav_1_1_compact_span.html", "struct_sharp_nav_1_1_compact_span" ],
    [ "CompactSpanReference", "struct_sharp_nav_1_1_compact_span_reference.html", "struct_sharp_nav_1_1_compact_span_reference" ],
    [ "Contour", "class_sharp_nav_1_1_contour.html", "class_sharp_nav_1_1_contour" ],
    [ "ContourSet", "class_sharp_nav_1_1_contour_set.html", "class_sharp_nav_1_1_contour_set" ],
    [ "ContourVertex", "struct_sharp_nav_1_1_contour_vertex.html", "struct_sharp_nav_1_1_contour_vertex" ],
    [ "Heightfield", "class_sharp_nav_1_1_heightfield.html", "class_sharp_nav_1_1_heightfield" ],
    [ "HeightPatch", "class_sharp_nav_1_1_height_patch.html", "class_sharp_nav_1_1_height_patch" ],
    [ "NavMesh", "class_sharp_nav_1_1_nav_mesh.html", "class_sharp_nav_1_1_nav_mesh" ],
    [ "NavMeshBuilder", "class_sharp_nav_1_1_nav_mesh_builder.html", "class_sharp_nav_1_1_nav_mesh_builder" ],
    [ "NavMeshGenerationSettings", "class_sharp_nav_1_1_nav_mesh_generation_settings.html", "class_sharp_nav_1_1_nav_mesh_generation_settings" ],
    [ "NavMeshQuery", "class_sharp_nav_1_1_nav_mesh_query.html", "class_sharp_nav_1_1_nav_mesh_query" ],
    [ "Node", "class_sharp_nav_1_1_node.html", "class_sharp_nav_1_1_node" ],
    [ "NodePool", "class_sharp_nav_1_1_node_pool.html", "class_sharp_nav_1_1_node_pool" ],
    [ "PolyBounds", "struct_sharp_nav_1_1_poly_bounds.html", "struct_sharp_nav_1_1_poly_bounds" ],
    [ "PolyMesh", "class_sharp_nav_1_1_poly_mesh.html", "class_sharp_nav_1_1_poly_mesh" ],
    [ "PolyMeshDetail", "class_sharp_nav_1_1_poly_mesh_detail.html", "class_sharp_nav_1_1_poly_mesh_detail" ],
    [ "PolyVertex", "struct_sharp_nav_1_1_poly_vertex.html", "struct_sharp_nav_1_1_poly_vertex" ],
    [ "Region", "class_sharp_nav_1_1_region.html", "class_sharp_nav_1_1_region" ],
    [ "RegionId", "struct_sharp_nav_1_1_region_id.html", "struct_sharp_nav_1_1_region_id" ],
    [ "Span", "struct_sharp_nav_1_1_span.html", "struct_sharp_nav_1_1_span" ],
    [ "SpanReference", "struct_sharp_nav_1_1_span_reference.html", "struct_sharp_nav_1_1_span_reference" ],
    [ "TiledNavMesh", "class_sharp_nav_1_1_tiled_nav_mesh.html", "class_sharp_nav_1_1_tiled_nav_mesh" ]
];